FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["food-delivery.csproj", "."]
RUN dotnet restore "./food-delivery.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "food-delivery.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "food-delivery.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "food-delivery.dll"]