version: "3.9"  # optional since v1.27.0
services:
  food-delivery:
    image: food-delivery
    container_name: food-delivery_application
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    user: root
    environment:
      - SA_PASSWORD=A&VeryComplex123Password
      - ACCEPT_EULA=y
  
  
  